add lecture05.md
satoru-AWS/RaiseTech-Assignment pull request #4
Opened 2024-02-29 12:54 UTC by satoru-AWS

lsson5

2024-03-05 03:17 UTC, MasatoshiMizumoto reviewed
途中からアプリケーションのUIスタイルが崩れているのですが、
崩れない想定なので、こちらの対処をお願いします！！

2024-03-07 14:03 UTC, satoru-AWS commented
unicorn+nginxでのデプロイ及びALB追加後のデプロイに関する画像を差し替えました。

2024-03-07 14:27 UTC, MasatoshiMizumoto requested changes
`.DS_Store`はMac専用で開発に使わないファイルなので、含まれないように対応いただきたいです！

2024-03-07 15:00 UTC, satoru-AWS commented
.DS_Storeファイルを除きましたので、再度確認をお願いします。

2024-03-07 15:14 UTC, MasatoshiMizumoto approved these changes
LGTMです！
![LGTM](https://lgtmoon.herokuapp.com/images/16512)

2024-03-10 08:29 UTC, merged